env:
  browser: true
  node: true
  es2022: true

root: true

extends:
  - eslint:recommended
  - plugin:astro/recommended

plugins:
  - simple-import-sort
  - import

parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module

settings:
  react:
    pragma: "h"
    version: "18.0"

rules:
  "import/first": "warn"
  "simple-import-sort/imports": "warn"
  "simple-import-sort/exports": "warn"
  "no-unused-vars": "off"
  "@typescript-eslint/no-unused-vars":
    - error
    - argsIgnorePattern: "^_"
      destructuredArrayIgnorePattern: "^_"

overrides:
  - files:
      - "*.astro"
    parser: "astro-eslint-parser"
    parserOptions:
      parser: "@typescript-eslint/parser"
      extraFileExtensions:
        - ".astro"
    rules:
      # Astro cannot deal with imports on the first line because of the first line having to be ---
      "import/first": off
  - files:
      - "*.ts"
    parser: "@typescript-eslint/parser"
    extends:
      - "plugin:@typescript-eslint/recommended"
  - files:
      - "*.d.ts"
    rules:
      "@typescript-eslint/triple-slash-reference": off
  - files:
      - "*.tsx"
    plugins:
      - "react"
      - "@typescript-eslint"
    extends:
      - "eslint:recommended"
      - "plugin:react/recommended"
      - "plugin:react/jsx-runtime"
      - "plugin:@typescript-eslint/recommended"
      - "plugin:@typescript-eslint/recommended-requiring-type-checking"
    parser: "@typescript-eslint/parser"
    parserOptions:
      project: tsconfig.json
  - files:
      - "**/*.astro/*.js"
      - "*.astro/*.js"
    parser: "@typescript-eslint/parser"
