name: '[📝] 6. Other Issue'
description: If you have an issue with the wiki that doesn't fit into the other templates
type: task
body:
  - type: textarea
    id: text
    attributes:
      label: Description
      description: Describe the issue you're facing
    validations:
      required: true
  - type: textarea
    id: debug
    attributes:
      label: Debug information
      description: 'Visit the [debug page](https://minecolonies.com/debug#browser-information), click the "Browser information" block to copy it, and paste the output here. This helps us identify device and browser related issues.'
