name: Verify
description: Verify the repository

runs:
  using: composite
  steps:
    - name: Configure NodeJS
      uses: actions/setup-node@v6
      with:
        node-version: 22.x
        check-latest: false

    - name: Configure pnpm
      uses: pnpm/action-setup@v6

    - name: Install
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Lint
      shell: bash
      run: pnpm run lint
