name: Verify linter

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Configure NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: 25.x
          check-latest: false

      - name: Configure pnpm
        uses: pnpm/action-setup@v4

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint
