name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/verify

  tag:
    needs: verify
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    outputs:
      tag: ${{ steps.tag.outputs.new_tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          GIT_API_TAGGING: false

  publish:
    needs: tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Process repository name
        run: echo "IMAGE_PATH=${REGISTRY}/${IMAGE_NAME@L}" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_PATH }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.IMAGE_PATH }}:${{ needs.tag.outputs.tag }}
          labels: ${{ steps.meta.outputs.labels }}

  chart:
    needs:
      - tag
      - publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      statuses: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Helm Chart Version
        working-directory: chart/wiki
        run: |
          echo "Updating Chart.yaml version to ${{ needs.tag.outputs.tag }}"
          sed -i "s/^version: \(.*\)/version: ${{ needs.tag.outputs.tag }}/g" Chart.yaml
          sed -i "1s/version: v\(.*\)/version: \1/g" Chart.yaml

      - name: Add Bitnami chart repository
        run: helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Install chart dependencies
        run: helm dependency update chart/wiki

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: chart
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
